spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: wiz

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:23306/doram
    username: root
    password: 1234
    hikari: # DB Pool Size
      minimum-idle: 2
      maximum-pool-size: 5
  jpa:
    hibernate:
      #ddl option: none || validate || update | create | create-drop
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 12000
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

logging:
  level:
    org:
      springframework:
        security:
          web: trace
